# Generated by Django 5.2.4 on 2025-08-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='firmware/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
