# Generated by Django 5.1.4 on 2025-08-06 07:34

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='firmware/'),
        ),
    ]
