# Generated by Django 5.2.7 on 2025-11-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0002_alter_firmware_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='device_version',
            field=models.CharField(blank=True, null=True),
        ),
    ]
